import Vue from 'vue'
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      redirect:'/index',
      component: HelloWorld,
      children:[
        {
          path:'/index',
          name:'index',
          component:()=>import('@/components/index')
        },
        {
          path:'/notice',
          name:'notice',
          component:()=>import('@/components/notice')
        },
        {
          path:'/myparty',
          name:'myparty',
          component:()=>import('@/components/myparty')
        },
      ]
    },
    {
      path:'/login',
      name:'login',
      component:()=>import('@/home/login')
    },
    {
      path:'/notice-detail',
      name:'notice-detail',
      component:()=>import('@/components/notice-detail')
    },
    {
      path:'/newseye',
      name:'newseye',
      component:()=>import('@/home/newseye')
    },
    {
      path:'/eyes-detail',
      name:'eyes-detail',
      component:()=>import('@/home/eyes-detail')
    },
    {
      path:'/history',
      name:'history',
      component:()=>import('@/home/history')
    },
    {
      path:'/interaction',
      name:'interaction',
      component:()=>import('@/home/interaction')
    },
    {
      path:'/point',
      name:'point',
      component:()=>import('@/news/point')
    },
    {
      path:'/point-detail',
      name:'point-detail',
      component:()=>import('@/news/point-detail')
    },
    {
      path:'/member',
      name:'member',
      component:()=>import('@/news/member')
    },
    {
      path:'/member-detail',
      name:'member-detail',
      component:()=>import('@/news/member-detail')
    },
    {
      path:'/life',
      name:'life',
      component:()=>import('@/life/life')
    },
    {
      path:'/study',
      name:'study',
      component:()=>import('@/life/study')
    },
    {
      path:'/study-detail',
      name:'study-detail',
      component:()=>import('@/life/study-detail')
    },
    {
      path:'/map',
      name:'map',
      hidden:true,
      component:()=>import('@/life/Map')
    },
    {
      path:'/reports',
      name:'reports',
      component:()=>import('@/life/reports')
    },
    {
      path:'/heart',
      name:'heart',
      component:()=>import('@/life/heart')
    },
    {
      path:'/updatepwd',
      name:'updatepwd',
      component:()=>import('@/myParty/updatepwd')
    },
    {
      path:'/scores',
      name:'scores',
      component:()=>import('@/myParty/scores')
    },
    {
      path:'/scores-detail',
      name:'scores-detail',
      component:()=>import('@/myParty/score-detail')
    },
    {
      path:'/inform',
      name:'inform',
      component:()=>import('@/myParty/information')
    },
    {
      path:'/info-edit',
      name:'info-edit',
      component:()=>import('@/myParty/info-edit')
    },
    {
      path:'/interact-detail',
      name:'interact-detail',
      component:()=>import('@/home/interact-detail')
    },
  ]
})
